RedHatQE/openshift-python-utilities

- .github/workflows/upload-to-pypi.yml
- .readthedocs.yaml
- .release-it.json
- README.md
- setup.cfg
> Add release-it and pypi

- ocp_utilities/infra.py
> Logger - add setup_logger

- ocp_utilities/file_utils.py
- ocp_utilities/logger.py
- ocp_utilities/pytest_utils.py
> Fix logger in 4.11

- ocp_utilities/must_gather.py
> Add --insecure-skip-tls-verify in must_gather

- ocp_utilities/must_gather.py
> Add skip_tls_check to save_must_gather_logs

- ocp_utilities/must_gather.py
> Must-gather - set image_url as optional

- README.md
> Update README - remove wip

- ocp_utilities/must_gather.py
- ocp_utilities/utils.py
Remove extra dir and cmd function
> Remove extra dir in must_gather

- README.md
- ocp_utilities/data-collector.yaml
- ocp_utilities/data-collector.yaml.example
- ocp_utilities/data_collector.py
- ocp_utilities/infra.py
- requirements.txt
- setup.py
> Add data collector

- setup.cfg
Remove version from setup.cfg in main branch
We do not release from main branch.
> Remove version from setup.cfg

- ocp_utilities/debugger.py
- requirements.txt
pytest --pdbcls=ocp_utilities.debugger:WebDebugger --pdb
> add remote python debugger

- ocp_utilities/debugger.py
- requirements.txt
add remote python debugger (#70)
>  add remote python debugger

- ocp_utilities/infra.py
DynamicClassCreator: use self.res to match https://github.com/RedHatQE/openshift-python-wrapper/pull/945
> DynamicClassCreator: Use self.res

- ocp_utilities/data_collector.py
> Add open mode to write_to_file function

- requirements.txt
- setup.py
Add openshift-python-wrapper to requirements.txt and setup.py
> Add openshift-python-wrapper as required

- tox.ini
> Add flake8 to tox.ini

- ocp_utilities/infra.py
> assert_pods_failed_or_pending - add pod namespace

- ocp_utilities/utils.py
> run_command - add command timeout

- ocp_utilities/operators.py
> Add uninstall_operator function

- ocp_utilities/operators.py
> operator functions - set defaults

- ocp_utilities/infra.py
Adding support for ImageContentSourcePolicy creation
> adding ICSP config utilities

- ocp_utilities/operators.py
Allow passing explicit ns for the operator
> install_operator - add operator ns

- ocp_utilities/infra.py
- update pull-secret with new content using it's data as environment variable
> Support for creating/updating secrets

- ocp_utilities/operators.py
> Add operator_namespace to uninstall_operator

- ocp_utilities/monitoring.py
Added the functions wait_for_alert_by_state_sampler and get_alerts_by_state in monitor.py,
Added the option to check for alerts with other states than only firing.
I've been testing alerts, and I needed a to check alerts that have 
a long evaluation time, in this cases we check for pending state, so I tried to add
that option and it was very handy while working with alerts.
> Added wait_for_alert_by_state_sampler  and get_alerts_by_state for adding the option for checking alerts in any state

- .flake8
- ocp_utilities/infra.py
- ocp_utilities/operators.py
> Ignore urllib3 `InsecureRequestWarning` warnings

- ocp_utilities/operators.py
> Add wait for subscription installedCSV

- ocp_utilities/infra.py
- ocp_utilities/operators.py
> Add admin client to resources

- ocp_utilities/cluster_versions.py
Fix https://github.com/RedHatQE/ci-jobs-trigger/issues/96
> `parse_openshift_release_url` disable cache

- ocp_utilities/cluster_versions.py
> get_accepted_cluster_versions - add explanation on streams

- ocp_utilities/must_gather.py
> add since and timeout switch to must-gather
